create table public.customers (
  id uuid not null default extensions.uuid_generate_v4 (),
  product_id uuid not null,
  external_ref character varying(100) null,
  name character varying(255) not null,
  email character varying(255) not null,
  cpf_cnpj character varying(20) not null,
  phone character varying(20) null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  plan_id uuid null,
  provider_beneficiary_id character varying(100) null,
  gateway_id character varying(100) null,
  birth_date text null,
  gender bigint null,
  subscription_id character varying(50) null,
  status character varying(20) null,
  street character varying(255) null,
  number character varying(20) null,
  complement character varying(255) null,
  district character varying(100) null,
  city character varying(100) null,
  state character varying(2) null,
  zip_code character varying(10) null,
  terms_accepted boolean null default false,
  terms_accepted_at timestamp without time zone null,
  terms_version character varying(50) null,
  constraint customers_pkey primary key (id),
  constraint customers_product_id_email_key unique (product_id, email),
  constraint customers_plan_id_fkey foreign KEY (plan_id) references plans (id),
  constraint customers_product_id_fkey foreign KEY (product_id) references products (id)
) TABLESPACE pg_default;

create index IF not exists idx_customers_provider_beneficiary_id on public.customers using btree (provider_beneficiary_id) TABLESPACE pg_default;